### ISSUE TITLE
Crash with QuackLib

### ISSUE THREAD

**Issue by dblsaiko** [dblsaiko/QuackLib#3]
Imported from [QuackLib#4](https://gitlab.com/the_real_farfetchd/QuackLib/issues/4)

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.6.0.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 1/31/18 12:13 PM
Description: Initializing game

java.lang.NoSuchMethodError: therealfarfetchd.quacklib.common.api.qblock.WrapperImplManager.item$default(Ltherealfarfetchd/quacklib/common/api/qblock/WrapperImplManager;Lkotlin/reflect/KClass;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)Lkotlin/Lazy;
	at therealfarfetchd.retrocomputers.common.block.Backplane.<clinit>(Backplane.kt:66)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at therealfarfetchd.quacklib.common.api.util.AutoRegistryKt.findClass(AutoRegistry.kt:217)
	at therealfarfetchd.quacklib.common.api.util.AutoRegistryKt.access$findClass(AutoRegistry.kt:1)
	at therealfarfetchd.quacklib.common.api.util.IBlockDefinition$Companion$populateBlockDefs$mainClass$1.invoke(AutoRegistry.kt:69)
	at therealfarfetchd.quacklib.common.api.util.IBlockDefinition$Companion$populateBlockDefs$mainClass$1.invoke(AutoRegistry.kt:59)
	at therealfarfetchd.quacklib.common.api.util.AutoRegistryKt.shutupForge(AutoRegistry.kt:238)
	at therealfarfetchd.quacklib.common.api.util.IBlockDefinition$Companion.populateBlockDefs(AutoRegistry.kt:69)
	at therealfarfetchd.quacklib.common.Proxy.registerBlocks(Proxy.kt:143)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_237_Proxy_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at therealfarfetchd.retrocomputers.common.block.Backplane.<clinit>(Backplane.kt:66)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at therealfarfetchd.quacklib.common.api.util.AutoRegistryKt.findClass(AutoRegistry.kt:217)
	at therealfarfetchd.quacklib.common.api.util.AutoRegistryKt.access$findClass(AutoRegistry.kt:1)
	at therealfarfetchd.quacklib.common.api.util.IBlockDefinition$Companion$populateBlockDefs$mainClass$1.invoke(AutoRegistry.kt:69)
	at therealfarfetchd.quacklib.common.api.util.IBlockDefinition$Companion$populateBlockDefs$mainClass$1.invoke(AutoRegistry.kt:59)
	at therealfarfetchd.quacklib.common.api.util.AutoRegistryKt.shutupForge(AutoRegistry.kt:238)
	at therealfarfetchd.quacklib.common.api.util.IBlockDefinition$Companion.populateBlockDefs(AutoRegistry.kt:69)
	at therealfarfetchd.quacklib.common.Proxy.registerBlocks(Proxy.kt:143)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_237_Proxy_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-112-generic
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 268324184 bytes (255 MB) / 657321984 bytes (626 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2604 Optifine OptiFine_1.12.2_HD_U_C8 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version          | Source                                            | Signature                                |
	|:----- |:-------------------- |:---------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2           | minecraft.jar                                     | None                                     |
	| UCH   | mcp                  | 9.42             | minecraft.jar                                     | None                                     |
	| UCH   | FML                  | 8.0.99.99        | forge-1.12.2-14.23.1.2604.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.1.2604     | forge-1.12.2-14.23.1.2604.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | opencomputers|core   | 1.7.1.43         | minecraft.jar                                     | None                                     |
	| UCH   | akashictome          | 1.2-10           | AkashicTome-1.2-10.jar                            | None                                     |
	| UCH   | cd4017be_lib         | 6.0.8            | CD4017BE_lib-1.12.2-6.0.8.jar                     | None                                     |
	| UCH   | circuits             | 6.1.0            | AutomatedRedstone-1.12.2-6.1.0.jar                | None                                     |
	| UCH   | autoreglib           | 1.3-15           | AutoRegLib-1.3-15.jar                             | None                                     |
	| UCH   | buildcraftlib        | 7.99.13          | buildcraft-core-7.99.13.jar                       | None                                     |
	| UCH   | buildcraftcore       | 7.99.13          | buildcraft-core-7.99.13.jar                       | None                                     |
	| UCH   | buildcraftenergy     | 7.99.13          | buildcraft-energy-7.99.13.jar                     | None                                     |
	| UCH   | chiselsandbits       | 14.12            | chiselsandbits-14.12.jar                          | None                                     |
	| UCH   | compactmachines3     | 3.0.5            | compactmachines3-1.12.2-3.0.5-b184.jar            | None                                     |
	| UCH   | crafttweaker         | 4.0.12           | CraftTweaker2-1.12-4.0.12.jar                     | None                                     |
	| UCH   | ctgui                | 1.0.0            | CraftTweaker2-1.12-4.0.12.jar                     | None                                     |
	| UCH   | jei                  | 4.8.5.147        | jei_1.12.2-4.8.5.147.jar                          | None                                     |
	| UCH   | crafttweakerjei      | 2.0.0            | CraftTweaker2-1.12-4.0.12.jar                     | None                                     |
	| UCH   | extrabitmanipulation | 1.12-3.2.1       | ExtraBitManipulation-1.12-3.2.1.jar               | None                                     |
	| UCH   | forgelin             | 1.6.0            | Forgelin-1.6.0.jar                                | None                                     |
	| UCH   | hatchery             | 2.1.2            | hatchery-1.12.2-2.1.2.jar                         | None                                     |
	| UCH   | igwmod               | 1.4.3-14         | IGW-Mod-1.12.2-1.4.3-14-universal.jar             | None                                     |
	| UCH   | ic2                  | 2.8.50-ex112     | industrialcraft-2-2.8.50-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | mantle               | 1.12-1.3.1.21    | Mantle-1.12-1.3.1.21.jar                          | None                                     |
	| UCH   | mcmultipart          | 2.4.1_60         | MCMultiPart-exp-2.4.1_60.jar                      | None                                     |
	| UCH   | minecoprocessors     | 1.12.2-4         | minecoprocessors-1.12.2-4.jar                     | None                                     |
	| UCH   | mtrm                 | 1.2.2.30         | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar        | None                                     |
	| UCH   | opencomputers        | 1.7.1.43         | OpenComputers-MC1.12.1-1.7.1.43.jar               | None                                     |
	| UCH   | redstoneflux         | 2.0.1            | RedstoneFlux-1.12-2.0.1.2-universal.jar           | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | p455w0rdslib         | 2.0.24           | p455w0rdslib-1.12-2.0.24.jar                      | None                                     |
	| UCH   | pneumaticcraft       | 1.12.2-0.3.1-125 | pneumaticcraft-repressurized-1.12.2-0.3.1-125.jar | None                                     |
	| UCH   | quacklib             | 2.0.0            | quacklib-2.0.0.jar                                | None                                     |
	| UCH   | retrocomputers       | 2.0.0            | RetroComputers-2.0.0.jar                          | None                                     |
	| UCH   | rftools              | 7.23             | rftools-1.12-7.23.jar                             | None                                     |
	| UCH   | rftoolscontrol       | 1.8.0            | rftoolsctrl-1.12-1.8.0.jar                        | None                                     |
	| UCH   | rftoolsdim           | 5.50             | rftoolsdim-1.12-5.50.jar                          | None                                     |
	| UCH   | rswires              | 1.0.0            | rswires-1.0.0.jar                                 | None                                     |
	| UCH   | sonarcore            | 5.0.3            | sonarcore-1.12.2-5.0.3.jar                        | None                                     |
	| UCH   | teckle               | 1.12.1           | teckle-1.12-5.394.jar                             | None                                     |
	| UCH   | theoneprobe          | 1.4.19           | theoneprobe-1.12-1.4.19.jar                       | None                                     |
	| UCH   | tis3d                | 1.3.1.17         | TIS-3D-MC1.12-1.3.1.17.jar                        | None                                     |
	| UCH   | topaddons            | 1.12.2-1.2.1     | topaddons-1.12.2-1.2.1.jar                        | None                                     |
	| UCH   | wearablebackpacks    | 3.1.0            | WearableBackpacks-1.12.2-3.1.0.jar                | None                                     |
	| UCH   | xaerominimap         | 1.14.5           | Xaeros_Minimap_1.14.5_Forge_1.12.jar              | None                                     |
	| UCH   | xnet                 | 1.6.7            | xnet-1.12-1.6.7.jar                               | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.6.0.jar)
  
TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 12.0.6' Renderer: 'Mesa DRI Intel(R) Sandybridge Mobile '
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2604
	LWJGL: 2.9.4
	OpenGL: Mesa DRI Intel(R) Sandybridge Mobile  GL version 3.0 Mesa 12.0.6, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 4
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.0 Mesa 12.0.6
	OpenGlRenderer: Mesa DRI Intel(R) Sandybridge Mobile 
	OpenGlVendor: Intel Open Source Technology Center
	CpuCount: 4
```

**Comment by dblsaiko** [comment]
Closed because of inactivity
