### ISSUE TITLE
Alloy smelter crashes in Refined Storage

### ISSUE THREAD

**Issue by Knito58** [dblsaiko/QuackLib#6]
I hooked up the smelter with Refined Storage: A crafter on top and an importer to the bottom. When crafting the redstone ingot with Refined Storage this happened:

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.util.NonNullList.get(SourceFile:44)
	at therealfarfetchd.quacklib.common.api.recipe.OreDictTemplate$stack$2.invoke(AlloyRecipeTemplate.kt:50)
	at therealfarfetchd.quacklib.common.api.recipe.OreDictTemplate$stack$2.invoke(AlloyRecipeTemplate.kt:47)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at therealfarfetchd.quacklib.common.api.recipe.OreDictTemplate.getStack(AlloyRecipeTemplate.kt)
	at therealfarfetchd.quacklib.common.api.recipe.OreDictTemplate.makeStack(AlloyRecipeTemplate.kt:61)
	at therealfarfetchd.quacklib.common.api.recipe.AlloyFurnaceRecipes.findRecipe(AlloyFurnaceRecipes.kt:34)
	at therealfarfetchd.quacklib.common.block.BlockAlloyFurnace.func_73660_a(BlockAlloyFurnace.kt:82)
	at therealfarfetchd.quacklib.common.api.qblock.ITickingQBTile$DefaultImpls.update(ITickingQBTile.kt:12)
	at therealfarfetchd.quacklib.common.api.qblock.QBContainerTileInventory$Ticking.func_73660_a(QBContainerTileInventory.kt:124)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

Versions:

QuackLib 2.1.1
Redstone Wires 3.0.0
Forgelin 1.6.0
Forge 14.23.2.2654
Minecraft 1.12.2

**Comment by dblsaiko** [comment]
Strange that this happens, but easy fix.
